<section class="photoalbum">
<h2>Изменить альбом</h2>
<?php if ($this->error): ?>
<p class="error">
There were one or more issues with your submission.
Please correct them as indicated below.
</p>
<?php endif ?>
<?php
$form = $this->form;
$photoalbum_id = $this->photoalbum_id;
$photoalbum = $this->photoalbum;
$form->prepare();
$form->setAttribute('action', $this->url(NULL,
array('controller'=>'Photoalbum', 'action' => 'process', 'id' => $photoalbum_id)));
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
?>
<dl class="zend_form">
<dt><?php echo $this->formLabel($form->get('name')); ?></dt>
<dd><?php
echo $this->formElement($form->get('name'));
echo $this->formElementErrors($form->get('name'));
?></dd>
<dt><?php echo $this->formLabel($form->get('describes')); ?></dt>
<dd><?php
echo $this->formElement($form->get('describes'));
echo $this->formElementErrors($form->get('describes'));
?></dd>
<dt><?php echo $this->formLabel($form->get('ph_name')); ?></dt>
<dd><?php
echo $this->formElement($form->get('ph_name'));
echo $this->formElementErrors($form->get('ph_name'));
?></dd>
<dt><?php echo $this->formLabel($form->get('email')); ?>
</dt>
<dd><?php
echo $this->formElement($form->get('email'));
echo $this->formElementErrors($form->get('email'));
?></dd>
<dt><?php echo $this->formLabel($form->get('phone'));
?></dt>
<dd><?php
echo $this->formElement($form->get('phone'));
echo $this->formElementErrors($form->get('phone'));
?></dd>
<dd><?php
echo $this->formHidden($form->get('data_download'));
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('count')->setValue($photoalbum->count));
echo $this->formHidden($form->get('data_change')->setValue(date("Y.m.d")));
echo $this->formElement($form->get('submit')->setValue('Edit'));
echo $this->formElementErrors($form->get('submit'));
?></dd>
</dl>
<?php echo $this->form()->closeTag() ?>
</section>