<?php

 $title = 'Альбомы';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('photoalbum', array('action'=>'add'));?>">Add new album</a>
 </p>
 <p>
     <a href="<?php echo $this->url('photoalbum', array('action'=>'addphoto'));?>">Add new photo in the gallery</a>
 </p>
 <p>
     <a href="<?php echo $this->url('photoalbum', array('action'=>'media'));?>">Show Gallery</a>
 </p>
 <table class="table">
 <tr>
     <th>Title</th>
     <th>Data Change</th>
     <th>Photos in Album</th>
     <th>&nbsp;</th> 
     <th>Cover</th>                    
 </tr>
 <?php 

 foreach ($photoalbums as $photoalbum) :
  
            ?>
 <tr>
     <td><?php echo $this->escapeHtml($photoalbum->name);?></td>
     <td><?php echo $this->escapeHtml($photoalbum->data_change);?></td>
     <td><?php echo $this->escapeHtml($photoalbum->count);?></td>

     <td>
         <a href="<?php echo $this->url('photoalbum',
             array('action'=>'edit', 'id' => $photoalbum->id));?>">Edit</a>
         <a href="<?php echo $this->url('photoalbum',
             array('action'=>'delete', 'id' => $photoalbum->id));?>">Delete</a>
         <a href="<?php echo $this->url('photoalbum',
             array('action'=>'addphotos', 'id' => $photoalbum->id));?>">AddPhoto</a>
         <a href="<?php echo $this->url('photoalbum',
            array('action'=>'media', 'id' => $photoalbum->id));?>">ShowPhoto</a>
            </td>
       <td><img src="<?php echo $this->url('photoalbum', array('action'=>'showCover',
                                                            'id' => $photoalbum->id,
                                                            'subaction' => 'full'));?>" /></td>      
 </tr>
 <?php 
       endforeach; ?>


 </table>